version: "3.9"

services:
  mediscreen_sql_db:
    container_name: "mediscreen-sql-db"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mediscreen
      - POSTGRES_USER=mediscreen
      - POSTGRES_DB=mediscreen
    ports:
      - "5432:5432"
  mediscreen_microservice_users:
    build: ./microservice-users
    ports:
      - "8081:8081"
    container_name: "mediscreen-microservice-users"
  mediscreen_microservice_web:
    build: ./microservice-web
    ports:
      - "8080:8080"
    container_name: "mediscreen-microservice-web"