version: "3.9"

services:
  mediscreen_sql_db:
    container_name: "mediscreen-sql-db"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mediscreen
      - POSTGRES_USER=mediscreen
      - POSTGRES_DB=mediscreen
    ports:
      - "5432:5432"
  mediscreen_microservice_users:
    build: ./microservice-users
    ports:
      - "8081:8081"
    container_name: "mediscreen-microservice-users"
  mediscreen_microservice_web:
    build: ./microservice-web
    ports:
      - "8080:8080"
    container_name: "mediscreen-microservice-web"
  mediscreen_notes_db:
      container_name: "mediscreen-nosql-db"
      image: mongo
      environment:
        MONGO_INITDB_ROOT_PASSWORD: mediscreen
        MONGO_INITDB_ROOT_USERNAME: mediscreen
        MONGO_INITDB_DATABASE: mediscreen-db
      ports:
        - "27017:27017"
  mediscreen_mongo_express:
    image: mongo-express
    restart: always
    container_name: "mediscreen-mongo-express"
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mediscreen
      ME_CONFIG_MONGODB_ADMINPASSWORD: mediscreen
      ME_CONFIG_MONGODB_URL: mongodb://mediscreen:mediscreen@mediscreen-nosql-db:27017/
  mediscreen_microservice_notes:
    build: ./microservice-notes
    container_name: "mediscreen-microservice-notes"
    ports:
      - "8282:8282"
  mediscreen_microservice_report:
    build: ./microservice-report
    container_name: "mediscreen-microservice-report"
    ports:
      - "8083:8083"
