version: "3.9"

services:
  mediscreen_sql_db:
    container_name: "mediscreen_sql_db"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mediscreen
      - POSTGRES_USER=mediscreen
      - POSTGRES_DB=mediscreen
    ports:
      - "5432:5432"
  mediscreen_microservice_users:
    build: ./microservice-users
    ports:
      - "9002:9002"
    container_name: "mediscreen_microservice_users"